title: The Jazz Pianists
description: >
  Tracing the evolution of jazz piano, one pianist at a time.
baseurl: ""

favicon-directory: /assets/favicon/
assets-directory: /assets/
image-directory: /assets/
empty-array: []

social:
  github: https://github.com/legion80/jazzpianists-org
exclude:
  - README.md

plugins:
  - jekyll-feed

collections:
  genres:
    output: true
  people:
    output: true
  albums:
    output: true
  songs:
    output: true
collections_dir: collections
# permalink: pretty
# markdown: kramdown
# kramdown:
#     input: GFM
#
# paginate: 5
# paginate_path: "/some-path/page:num/"

defaults:
  - scope:
      path: ""
    values:
      layout: "page"
